* [[mu4e:msgid:3069E00B-EF53-4B5F-85EE-C709540AAF4D@tufts.edu][ziggy’s email]] about midterm contents

* extra time students
  - [[mu4e:msgid:CAATgJ2+XmjCSO99JHia84J4hvE+bwBcLoCDfv9M5cDW18jGFUg@mail.gmail.com][Sloan Woodberry]]

* thursday exams

  - [[mu4e:msgid:CCE1F24E-D4BC-4DC8-9F54-D0B0619890C1@tufts.edu][anna DeCotis]]
  
  - [[mu4e:msgid:BN7PR05MB57317014E76FAAC458285EED8FB39@BN7PR05MB5731.namprd05.prod.outlook.com][alexa watson]]

  - [[mu4e:msgid:74450DDB-F27A-4612-8652-58851C3FCEAD@tufts.edu][Shanni Zhou]]


Estended time (all +50%)
x	Adrien Amblard (also gets to use a computer, though he told me he doesn’t need it for this course)
x	Harry Davison
x	Julie Katz (also gets to use a calculator)
	Matt Rogoff
x	Elijah Sarvey

        Christof Inderbitzin
        Sloan Woodberry
	 
Conflict (so take exam on Thursday):
x	Shanni Zhou
x	Davonte Hudson
x	Anna DeCotis
x	Alexa Watson

* email text for extended time students
	
Greetings,

I’m writing because you are taking the Math51 Midterm Exam on
Wednesday Oct 20, and you have an extended-time accommodation.

Unless you’ve made arrangements to take the exam in the StAAR Center,
extended-time students should take the exam in Bromfield-Pearson Rm 1
(rather than Pearson Lab 104), starting at the exam time of 6:00 PM.

If you will instead take the exam in the StAAR Center, please let us
know!

All the best,
George McNinch

* email text for conflict students

Greetings,

I’m writing because you are taking the Math51 Midterm Exam on
Wednesday Oct 20, and you have a class conflicting with the exam.

So: you should instead take the exam on Thursday Oct 21 in
Bromfield-Pearson Rm 1, starting at 1:30 PM. 

My understanding is that everyone can make that starting time, but
please let me know if there is something I have forgotten.

All the best,
George McNinch


* ana decotis won’t start until 2:15

  [[mu4e:msgid:82a6j6p3v6.fsf@calliope][email]]
