
* [2021-10-19 Tue]

  Hello Tylee,

  I am sorry to hear this. My sincere condolences for your family’s loss.

  I have cc’d your Math 51 professor here so he is aware of your
  situation. Please note that I always tell students and faculty that
  part of what determines appropriate flexibility or accommodations is
  legitimacy of the extenuating circumstances and part is
  responsibility and timing on the part of the student - students must
  be proactive, communicate well with me and their faculty, and seek
  help responsibly. I did not hear about your health issues and the
  death in your family until this evening. As such, it is hard for me
  to advocate strongly for flexibility. That said, what may or may not
  be possible is ultimately determined by Professor McNinch’s course
  policies. I am not sure what they support. Professor McNinch if I
  may be of any assistance here please let me know.

  Tylee, if I may help further beyond Math 51, please let me know. For
  instance, you inquired about a temporary leave.  There is no formal
  such thing. However, we could meet to talk through your options for
  managing all that you’ve got going on including your academic
  responsibilities, which may include time away from campus.

  Best,
  Jennifer

  --------------------------------------------------------------------------------
  
  From: "Nez, Tylee T" <Tylee.Nez@tufts.edu>
  Date: Tuesday, October 19, 2021 at 5:34 PM
  To: "Stephan, Jennifer" <Jennifer.Stephan@tufts.edu>
  Subject: Re: Family 
  
  Hello, 
  
  Apologies for the doubling emailing. I have a midterm tomorrow for
  MATH 51 and I am not physically or mentally in the space to take an
  hour and 15-minute exam. This weekend and week I have been battling
  the flu which has been taking a huge toll on my body and a death in
  my family.

  Best, 

  Tylee Tosia Nez E'24 ​| Undergraduate Student

  Tufts University | Environmental Engineering & Civic Studies
  Anderson Hall | Medford, MA  02155
  Tylee.Nez@tufts.edu  | T:  520.310.8416 | LinkedIn |

  Pronouns: They/She

  
* [2021-10-20 Wed]

  Hello Professor McNinch, 

  I contacted Dean Stephan about a recent lost in my immediate
  family. This whole week I have been sick and today I have had a
  terrible headache. I am not mentally or physical capable of taking
  this exam. Are there any other opportunities to make up this exam.

  --------------------------------------------------------------------------------
  
  Tylee,

  There is already a group of students who had course-conflicts with
  the the scheduled exam, and will take the exam on Thursday
  (tomorrow) Oct 21.

  It will be in Bromfield-Pearson Rm. 1 at 1:30. If you don’t take the
  exam tonight, that is available.  It’ll give you another night to
  prepare.

  Let me know if you’d like to do that.

  Best,
  gm

  Thank you for providing accommodation. I plan on flying out tomorrow
  for the family emergency and would prefer to take it next week if
  that is possible.


* [2021-10-21 Thu] 

  Hello, 

  I had to change my flight last minute to this afternoon due to
  family news and not will be able to take the exam today.  Would I be
  able to take it next week when I return? Thank you again for
  providing accommodations through this very difficult time.

  Best, 
  Tylee 
  
